[package]
name = "grillon"
version = "0.5.0-alpha.1"
authors = ["theredfish <did.julian@gmail.com>"]
description = "Grillon offers an elegant and natural way to approach API testing in Rust."
repository = "https://github.com/owlduty/grillon"
keywords = ["test", "http", "api", "e2e"]
categories = ["development-tools::testing"]
readme = "README.md"
license = "MIT OR Apache-2.0"
include = ["/src", "LICENSE*", "README.md"]
edition = "2021"

[dependencies]
hyper = { version = "0.14.27", features = [
  "client",
  "http1",
  "http2",
  "runtime",
] }
hyper-tls = "0.5.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
http = "0.2.9"
url = "2.4.1"
futures = "0.3.28"
strum = { version = "0.25.0", features = ["derive"] }
strum_macros = "0.25.2"
jsonpath-rust = "0.3.1"
jsonschema = "0.17.1"

[dev-dependencies]
tokio = { version = "1.32.0", features = ["macros"] }
reqwest = { version = "0.11.20", features = ["json"] }
httpmock = "0.6.8"
async-trait = "0.1.73"
test-case = "3.1.0"
