[package]
name = "grillon"
version = "0.5.0-alpha.1"
authors = ["theredfish <did.julian@gmail.com>"]
description = "Grillon offers an elegant and natural way to approach API testing in Rust."
repository = "https://github.com/theredfish/grillon"
keywords = ["test", "http", "api", "e2e"]
categories = ["development-tools::testing"]
readme = "README.md"
license = "MIT OR Apache-2.0"
include = ["/src", "LICENSE*", "README.md"]
edition = "2021"

[dependencies]
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
http = "1.1.0"
url = "2.4.1"
futures = "0.3.28"
strum = { version = "0.26.1", features = ["derive"] }
strum_macros = "0.26.1"
jsonpath-rust = "0.5.0"
jsonschema = "0.19.1"
reqwest = { version = "0.12.7", features = ["json"] }
thiserror = "1.0.63"

[dev-dependencies]
tokio = { version = "1.40.0", features = ["macros"] }
httpmock = "0.7.0"
async-trait = "0.1.74"
test-case = "3.2.1"
surf = "2.3.2"
