[package]
name = "grillon"
version = "0.4.0-dev"
authors = ["theredfish <did.julian@gmail.com>"]
description = "Grillon offers an elegant and natural way to approach end-to-end HTTP API testing in Rust."
repository = "https://github.com/theredfish/grillon"
keywords = ["test", "http", "e2e", "end-to-end"]
categories = ["development-tools::testing"]
readme = "README.md"
license = "MIT OR Apache-2.0"
include = [
  "/src",
  "LICENSE*",
  "README.md"
]
edition = "2021"

[dependencies]
hyper = { version = "0.14.7", features = ["client", "http1", "http2", "runtime"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
http = "0.2.7"
url = "2.2.2"
futures = "0.3.21"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24.2"

[dev-dependencies]
tokio = { version = "1.18.2", features = ["macros"] }
reqwest = { version = "0.11.10", features = ["json"] }
httpmock = "0.6.6"
async-trait = "0.1.53"
test-case = "2.2.1"
