[package]
name = "grillon"
version = "0.4.0"
authors = ["theredfish <did.julian@gmail.com>"]
description = "Grillon offers an elegant and natural way to approach API testing in Rust."
repository = "https://github.com/owlduty/grillon"
keywords = ["test", "http", "e2e", "end-to-end"]
categories = ["development-tools::testing"]
readme = "README.md"
license = "MIT OR Apache-2.0"
include = [
  "/src",
  "LICENSE*",
  "README.md"
]
edition = "2021"

[dependencies]
hyper = { version = "0.14.23", features = ["client", "http1", "http2", "runtime"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
http = "0.2.8"
url = "2.3.1"
futures = "0.3.25"
strum = { version = "0.24.1", features = ["derive"] }
strum_macros = "0.24.3"

[dev-dependencies]
tokio = { version = "1.24.2", features = ["macros"] }
reqwest = { version = "0.11.14", features = ["json"] }
httpmock = "0.6.7"
async-trait = "0.1.63"
test-case = "3.0.0"
