[package]
name = "grillon"
version = "0.4.0"
authors = ["theredfish <did.julian@gmail.com>"]
description = "Grillon offers an elegant and natural way to approach API testing in Rust."
repository = "https://github.com/owlduty/grillon"
keywords = ["test", "http", "e2e", "end-to-end"]
categories = ["development-tools::testing"]
readme = "README.md"
license = "MIT OR Apache-2.0"
include = [
  "/src",
  "LICENSE*",
  "README.md"
]
edition = "2021"

[dependencies]
hyper = { version = "0.14.26", features = ["client", "http1", "http2", "runtime"] }
hyper-tls = "0.5.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
http = "0.2.9"
url = "2.3.1"
futures = "0.3.28"
strum = { version = "0.25.0", features = ["derive"] }
strum_macros = "0.25.0"
jsonpath-rust = "0.3.0"
jsonschema = "0.17.0"

[dev-dependencies]
tokio = { version = "1.28.1", features = ["macros"] }
reqwest = { version = "0.11.18", features = ["json"] }
httpmock = "0.6.7"
async-trait = "0.1.68"
test-case = "3.1.0"
