[package]
name = "grillon"
version = "0.3.0"
authors = ["theredfish <did.julian@gmail.com>"]
description = "Grillon offers an elegant and natural way to approach end-to-end HTTP API testing in Rust."
repository = "https://github.com/theredfish/grillon"
keywords = ["test", "http", "e2e", "end-to-end"]
categories = ["development-tools::testing"]
readme = "README.md"
license = "MIT OR Apache-2.0"
include = [
  "/src",
  "LICENSE*",
  "README.md"
]
edition = "2021"

[dependencies]
hyper = { version = "0.14.7", features = ["client", "http1", "http2", "runtime"] }
serde = "1.0.125"
serde_json = "1.0.64"
http = "0.2.4"
url = "2.2.2"
futures = "0.3"
pretty_assertions = { version = "1.0.0", optional = true }

[dev-dependencies]
tokio = { version = "1.12", features = ["macros"] }
reqwest = { version = "0.11.4", features = ["json"] }
httpmock = "0.6.5"
async-trait = "0.1.52"

[features]
diff = ["pretty_assertions"]
