[tasks.book]
command = "mdbook"
args = ["serve", "book", "--open"]

[tasks.doc]
command = "cargo"
args = ["watch", "-x", "doc --all-features --no-deps --open"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--workspace", "--all-features", "--", "-D", "warnings"]

