[book]
authors = ["theredfish"]
language = "en"
multilingual = false
src = "src"
title = "Grillon - User Guide"

[output.html]
git-repository-url = "https://github.com/owlduty/grillon"

[output.html.playground]
runnable = false

[rust]
edition = "2021"
