name: Book gh-pages

on:
  push:
    branches: ["main"]
    tags: ["v*"]
    paths: ["book/**"]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      BOOK_VERSION: ${{ (startsWith(github.ref, 'refs/tags/v') && 'current') || 'dev' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.25"

      - run: mdbook build book -d version/$BOOK_VERSION

      - name: Deploy book
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/version
