name: Deploy

on:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  crate:
    name: Release on crates.io
    needs:
      - rustfmt
      - clippy
      - build-and-test
      - doc
      - audit
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish grillon
        run: cargo publish -p grillon --token ${{ secrets.CRATES_IO }}
